server:
  port: 8092
spring:
  datasource:
    url: jdbc:mysql://192.168.17.27:3306/test?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2b8
    username: root
    password: iptvadmin
seata:
  tx-service-group: my_test_tx_group
  application-id: order
  service:
    grouplist:
      default: 192.168.17.55:8091
    disable-global-transaction: false